'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http'),{spawn}=require('node:child_process');
const {start}=require('../source/entry.cjs'),M=require('../source/model.cjs');
const root=path.resolve(__dirname,'..'),source=path.join(root,'source'),runId='core-'+Date.now()+'-'+crypto.randomUUID().slice(0,8),run=path.join(root,'tests','runs',runId),dataRoot=path.join(run,'data');
const report={runId,startedAt:new Date().toISOString(),node:process.version,pid:process.pid,checks:[],children:[],cleanup:{}};let app,token,sourceBefore;const apps=new Set(),children=new Set();
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
async function fingerprint(){const result={};for(const n of (await fs.readdir(source)).sort()){const f=path.join(source,n);assert((await fs.lstat(f)).isFile());result[n]=sha(await fs.readFile(f));}return result;}
async function check(name,fn){const at=performance.now();try{await fn();report.checks.push({name,passed:true,milliseconds:Math.round(performance.now()-at)});console.log('PASS '+name);}catch(e){report.checks.push({name,passed:false,message:e.message});throw e;}}
async function open(data=dataRoot){const a=await start({dataRoot:data,packageRoot:source,port:0,instanceId:'rehearsal-test-'+crypto.randomUUID()});apps.add(a);return a;}
async function api(route,body,extra={},auth=token){const r=await fetch(app.url+route,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json','x-app-token':auth}),...extra},signal:AbortSignal.timeout(5000),...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let value;try{value=JSON.parse(text);}catch{value=text;}return{status:r.status,value,text,headers:r.headers};}
async function cli(args,expected=0,useUrl=true){return new Promise((resolve,reject)=>{const c=spawn(process.execPath,[path.join(source,'cli.cjs'),...(useUrl?['--url',app.url]:[]),...args],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});children.add(c);let out='',err='';c.stdout.on('data',d=>out+=d);c.stderr.on('data',d=>err+=d);const timer=setTimeout(()=>c.kill(),12000);c.on('error',reject);c.on('close',(code,signal)=>{clearTimeout(timer);children.delete(c);report.children.push({pid:c.pid,args,exitCode:code,signal});try{assert.equal(code,expected,err||out);assert(!out.includes(token),'Token printed');assert(!err.includes(token),'Token printed');resolve({value:JSON.parse(code===0?out:err),stdout:out,stderr:err});}catch(e){reject(e);}});});}
async function main(){await fs.mkdir(run,{recursive:true});sourceBefore=await fingerprint();report.sourceBefore=sourceBefore;
await check('Manifest ID, unchanged access and host v1 contract',async()=>{const m=JSON.parse(await fs.readFile(path.join(source,'im.json'),'utf8'));assert.equal(m.id,M.APP_ID);assert.equal(m.apiVersion,1);assert.deepEqual(m.permissions,['app-data:read-write','loopback:listen']);assert.deepEqual(m.dependencies,['node']);app=await open();assert.equal(new URL(app.url).hostname,'127.0.0.1');const h=(await api('/api/health')).value;assert.equal(h.app,M.APP_ID);token=h.token;assert.match(token,/^[a-f0-9]{64}$/);report.initialIdentity={app:h.app,instanceId:h.instanceId,url:app.url,pid:h.pid};});
await check('Fresh empty rehearsal workspace persists immediately',async()=>{const p=(await cli(['inspect'])).value;assert.equal(p.name,'My rehearsal desk');assert.deepEqual(p.songs,[]);assert.equal(p.revision,1);assert.deepEqual(JSON.parse(await fs.readFile(path.join(dataRoot,'project.json'),'utf8')),p);});
await check('Production UI assets, CSP and content-type protections',async()=>{for(const route of['/','/app.js','/style.css']){const r=await api(route);assert.equal(r.status,200);assert(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));assert.equal(r.headers.get('x-content-type-options'),'nosniff');}const h=(await api('/')).text;assert(h.includes('Your set list'));assert(h.includes('song-notes'));assert(h.includes('Export printable plan'));});
await check('Authentication, foreign origin and cross-site requests refused',async()=>{const p=(await api('/api/project')).value;for(const auth of['','0'.repeat(64)])assert.equal((await api('/api/project',p,{},auth)).status,401);assert.equal((await api('/api/project',p,{Origin:'http://127.0.0.1:1'})).status,403);assert.equal((await api('/api/health',undefined,{'Sec-Fetch-Site':'cross-site','Sec-Fetch-Mode':'navigate'})).status,403);assert.deepEqual((await api('/api/project')).value,p);});
await check('Foreign Host header refused',async()=>{const code=await new Promise((resolve,reject)=>{const req=http.get(app.url+'/api/health',{headers:{Host:'not-the-app.invalid'},timeout:5000},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.on('timeout',()=>req.destroy(Error('timeout')));});assert.equal(code,403);});
await check('Bad JSON, content type and oversized request refused',async()=>{for(const [payload,type,code] of [['{','application/json',400],['{}','text/plain',415],['x'.repeat(1048580),'application/json',413]]){const r=await fetch(app.url+'/api/project',{method:'POST',headers:{'Content-Type':type,'x-app-token':token},body:payload,signal:AbortSignal.timeout(5000)});assert.equal(r.status,code);await r.text();}});
await check('Schema, text, dates, ranges, duplicate IDs and unknown fields validated',async()=>{const p=(await api('/api/project')).value;const s={id:crypto.randomUUID(),title:'Bounds',artist:'',key:'',bpm:null,durationSeconds:180,practiceMinutes:10,focus:'',notes:''};const cases=[{...p,name:''},{...p,notes:22},{...p,sessionDate:'2026-02-30'},{...p,warmupMinutes:-1},{...p,breakMinutes:121},{...p,unknown:'x'},{...p,schemaVersion:2},{...p,goal:'x'.repeat(501)},{...p,notes:'x'.repeat(20001)},{...p,songs:Array(101).fill({})},{...p,songs:[s,s]},{...p,songs:[{...s,bpm:301}]},{...p,songs:[{...s,durationSeconds:0}]},{...p,songs:[{...s,practiceMinutes:1.5}]},{...p,songs:[{...s,id:'../project'}]},{...p,songs:[{...s,notes:'x'.repeat(5001)}]}];for(const b of cases)assert.equal((await api('/api/project',b)).status,422);assert.deepEqual((await api('/api/project')).value,p);});
await check('Empty set cannot export a misleading session plan',async()=>{const r=await cli(['export','--format','html','--revision','1'],1);assert.equal(r.value.error.code,'EMPTY_SET_LIST');});
await check('Requested operation: build set list, practice times and notes through finite CLI',async()=>{let r=await cli(['session','--name','Friday rehearsal','--date','2026-10-09','--goal','Tighten the transitions','--notes','Bring the capo & spare strings.','--warmup','5','--break','3','--revision','1']);assert.equal(r.value.revision,2);for(const [title,duration,practice]of[['Harbour Lights','3:40','12'],['Paper Satellites','3:05','8'],['Midnight Windows','4:00','10']])r=await cli(['song','add','--title',title,'--key','E minor','--bpm','100','--duration',duration,'--practice',practice,'--focus','Chorus transition','--notes','Start slowly, then full tempo.','--revision',String(r.value.revision)]);assert.equal(r.value.songs.length,3);assert.equal(r.value.revision,5);report.exampleSet=r.value.songs;});
await check('Reorder and narrow song edits preserve other fields',async()=>{let p=(await cli(['inspect'])).value;const id=p.songs[2].id;let q=(await cli(['song','move',id,'--to','1','--revision',String(p.revision)])).value;assert.equal(q.songs[0].id,id);const before=structuredClone(q);q=(await cli(['song','edit',id,'--focus','Final chorus','--notes','Hold the last chord.','--revision',String(q.revision)])).value;before.revision++;before.songs[0].focus='Final chorus';before.songs[0].notes='Hold the last chord.';assert.deepEqual(q,before);});
await check('Browser save endpoint and CLI read/write one saved state',async()=>{let p=(await api('/api/project')).value;p.notes='From browser controller: keep the final chord together.';const r=await api('/api/project',p);assert.equal(r.status,200);assert.deepEqual((await cli(['inspect'])).value,r.value);p=(await cli(['session','--goal','From CLI: clean starts and endings','--revision',String(r.value.revision)])).value;assert.deepEqual((await api('/api/project')).value,p);});
await check('Stale browser/CLI edits and exports return conflicts without mutations',async()=>{const p=(await api('/api/project')).value;assert.equal((await api('/api/project',{...p,revision:p.revision-1,name:'Do not save'})).status,409);for(const args of [['song','edit',p.songs[0].id,'--notes','Do not save'],['export','--format','json']])assert.equal((await cli([...args,'--revision',String(p.revision-1)],1)).value.error.code,'REVISION_CONFLICT');assert.deepEqual((await api('/api/project')).value,p);});
await check('Concurrent equal-revision mutations: exactly one succeeds',async()=>{const p=(await api('/api/project')).value;const results=await Promise.all(['A','B'].map(goal=>api('/api/action',{revision:p.revision,action:'session.update',patch:{goal}})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await api('/api/project')).value.revision,p.revision+1);});
await check('Computed plan is 10:45 performance and 38-minute rehearsal',async()=>{const q=(await cli(['plan'])).value;assert.equal(q.setDurationSeconds,645);assert.equal(q.practiceMinutes,30);assert.equal(q.totalMinutes,38);assert.deepEqual(q.blocks.map(b=>[b.type,b.startMinute,b.endMinute]),[['warmup',0,5],['song',5,15],['song',15,27],['break',27,30],['song',30,38]]);report.examplePlan=q;});
await check('Real HTML/JSON snapshots: content, escaping, checksum and downloads',async()=>{let p=(await cli(['inspect'])).value;p=(await cli(['song','edit',p.songs[0].id,'--notes','<script>danger()</script> & "quoted"\nSecond line.','--revision',String(p.revision)])).value;const exports=[];for(const format of['html','json']){const meta=(await cli(['export','--format',format,'--revision',String(p.revision)])).value;const bytes=await fs.readFile(path.join(dataRoot,meta.path));assert.equal(sha(bytes),meta.sha256);assert.equal(bytes.length,meta.bytes);assert.equal(meta.revision,p.revision);const r=await api(meta.url);assert.equal(r.status,200);assert.equal(sha(r.text),meta.sha256);assert((await api(meta.downloadUrl)).headers.get('content-disposition').startsWith('attachment'));if(format==='html'){assert(r.text.includes('&lt;script&gt;danger()&lt;/script&gt;'));assert(!r.text.includes('<script>'));assert(r.text.includes('38 min rehearsal'));assert(r.text.includes('0:30–0:38'));}else{assert.deepEqual(r.value.project,p);assert.equal(r.value.plan.totalMinutes,38);}exports.push(meta);}report.exports=exports;assert.equal((await cli(['exports'])).value.exports.length,2);assert.equal((await api('/api/project')).value.revision,p.revision);});
await check('Bad commands/options/positions/durations and non-loopback URL fail finitely',async()=>{const p=(await cli(['inspect'])).value;for(const args of [['song','move',p.songs[0].id,'--to','0'],['song','add','--title','Invalid','--duration','3:99'],['song','edit',p.songs[0].id,'--bpm','0'],['export','--format','exe'],['session','--unknown','x'],['nonesuch']])await cli(args,1);await cli(['--url','http://127.0.0.2:1234','inspect'],1,false);assert.deepEqual((await api('/api/project')).value,p);assert.equal((await cli(['help'],0,false)).value.app,M.APP_ID);const s=(await cli(['status'])).value;assert.equal(s.revision,p.revision);assert(!Object.hasOwn(s,'token'));});
await check('Export and static paths reject traversal/nonexistent IDs',async()=>{for(const route of['/api/exports/..%2fproject.json','/api/exports/00000000-0000-4000-8000-000000000000','/../entry.cjs','/api/exports/'+report.exports[0].id+'/extra'])assert.equal((await api(route)).status,404);});
await check('Restart preserves saved work/exports; old token expires; close is idempotent',async()=>{const before=(await cli(['inspect'])).value,oldUrl=app.url,oldToken=token;await app.close();await app.close();apps.delete(app);await assert.rejects(fetch(oldUrl+'/api/project',{signal:AbortSignal.timeout(1500)}));app=await open();token=(await api('/api/health')).value.token;assert.notEqual(token,oldToken);assert.deepEqual((await cli(['inspect'])).value,before);assert.equal((await cli(['exports'])).value.exports.length,2);assert.equal((await api('/api/project',before,{},oldToken)).status,401);report.restartedIdentity={url:app.url,instanceId:(await api('/api/health')).value.instanceId};});
await check('Later edits cannot change previous export snapshots',async()=>{const meta=report.exports[0],p=(await cli(['inspect'])).value;await cli(['session','--notes','Next rehearsal: revisit the final chorus.','--revision',String(p.revision)]);assert.equal(sha(await fs.readFile(path.join(dataRoot,meta.path))),meta.sha256);});
await check('Overlapping roots, linked storage and corrupt saved data fail closed',async()=>{await assert.rejects(start({dataRoot:path.join(source,'forbidden-data'),packageRoot:source,port:0,instanceId:'bad'}),e=>e.code==='OVERLAPPING_ROOTS');const invalid=path.join(run,'invalid-data');await fs.mkdir(invalid);await fs.writeFile(path.join(invalid,'project.json'),'{bad json');await assert.rejects(open(invalid));assert.equal(await fs.readFile(path.join(invalid,'project.json'),'utf8'),'{bad json');const target=path.join(run,'link-target'),link=path.join(run,'linked-data');await fs.mkdir(target);await fs.symlink(target,link,'junction');await assert.rejects(open(link),e=>e.code==='LINKED_STORAGE');await fs.unlink(link);});
await check('Legacy starter notes and revision are preserved',async()=>{const dir=path.join(run,'legacy-data');await fs.mkdir(dir);await fs.writeFile(path.join(dir,'project.json'),JSON.stringify({revision:4,name:'Old notes',notes:'Keep these notes.'}));const a=await open(dir);const p=await(await fetch(a.url+'/api/project')).json();assert.equal(p.notes,'Keep these notes.');assert.equal(p.name,'Old notes');assert.equal(p.revision,4);assert.deepEqual(p.songs,[]);await a.close();apps.delete(a);});
}
(async()=>{let failed=false;try{await main();}catch(e){failed=true;report.failure={message:e.message,stack:e.stack};console.error(e.stack);}finally{let closed=true;for(const a of apps)try{await a.close();}catch(e){failed=true;closed=false;report.cleanup.error=e.message;}apps.clear();report.cleanup.serversClosed=closed;for(const c of children)c.kill();report.cleanup.cliChildrenExited=children.size===0;try{report.sourceAfter=await fingerprint();report.sourceUnchanged=JSON.stringify(sourceBefore)===JSON.stringify(report.sourceAfter);assert(report.sourceUnchanged,'Source changed during tests');assert(report.cleanup.cliChildrenExited);}catch(e){failed=true;report.cleanup.error=e.message;}report.finishedAt=new Date().toISOString();report.passed=report.checks.filter(c=>c.passed).length;report.failed=report.checks.filter(c=>!c.passed).length;report.ok=!failed;await fs.mkdir(run,{recursive:true});await fs.writeFile(path.join(run,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:report.ok,passed:report.passed,failed:report.failed,report:path.relative(root,path.join(run,'result.json')),cleanup:report.cleanup,sourceUnchanged:report.sourceUnchanged},null,2));process.exitCode=failed?1:0;}})();
