'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const M=require('../source/model.cjs'),{start}=require('../source/entry.cjs');
const root=path.resolve(__dirname,'..'),source=path.join(root,'source');
const runId='duplicate-'+Date.now()+'-'+crypto.randomUUID().slice(0,8),run=path.join(root,'tests','runs',runId),dataRoot=path.join(run,'compatibility-data');
const report={runId,startedAt:new Date().toISOString(),node:process.version,checks:[],children:[],cleanup:{},fixtureProvenance:'Synthetic Tuesday practice fixture recreated inside this test; no live data read.'};
const apps=new Set(),children=new Set(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');let app,token,oldStart,oldExports=[],beforeHashes,fixture;
async function fingerprint(){const out={};for(const n of(await fs.readdir(source)).sort())out[n]=hash(await fs.readFile(path.join(source,n)));return out;}
async function check(name,fn){const at=performance.now();try{await fn();report.checks.push({name,passed:true,milliseconds:Math.round(performance.now()-at)});console.log('PASS '+name);}catch(e){report.checks.push({name,passed:false,message:e.message});throw e;}}
async function open(dir=dataRoot,entry=start,packageRoot=source){const a=await entry({dataRoot:dir,packageRoot,port:0,instanceId:'duplication-test-'+crypto.randomUUID()});apps.add(a);return a;}
async function close(a){await a.close();await assert.rejects(fetch(a.url+'/api/project',{signal:AbortSignal.timeout(1500)}));apps.delete(a);}
async function api(route,body,extra={},auth=token){const r=await fetch(app.url+route,{method:body===undefined?'GET':'POST',headers:body===undefined?extra:{'Content-Type':'application/json','x-app-token':auth,...extra},signal:AbortSignal.timeout(5000),...(body===undefined?{}:{body:JSON.stringify(body)})});const t=await r.text();let value;try{value=JSON.parse(t);}catch{value=t;}return{status:r.status,value,text:t};}
const inspect=async()=>{const r=await api('/api/project');assert.equal(r.status,200);return r.value;};
async function cli(args,expected=0){return new Promise((resolve,reject)=>{const c=spawn(process.execPath,[path.join(source,'cli.cjs'),'--url',app.url,...args],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});children.add(c);let stdout='',stderr='';c.stdout.on('data',d=>stdout+=d);c.stderr.on('data',d=>stderr+=d);const timer=setTimeout(()=>c.kill(),12000);c.once('error',reject);c.once('close',(code,signal)=>{clearTimeout(timer);children.delete(c);report.children.push({pid:c.pid,args,exitCode:code,signal});try{if(expected!==null)assert.equal(code,expected,stderr||stdout);assert(!token||!stdout.includes(token),'Token exposed');assert(!token||!stderr.includes(token),'Token exposed');resolve({code,value:JSON.parse(code===0?stdout:stderr)});}catch(e){reject(e);}});});}
function rehearsal(){return{schemaVersion:1,revision:5,name:'Tuesday practice',sessionDate:'',goal:'Tighten our transitions and finish together.',notes:'Demo rehearsal: two original placeholder songs.',warmupMinutes:5,breakMinutes:5,songs:[{id:crypto.randomUUID(),title:'Silver Compass',artist:'',key:'E minor',bpm:96,durationSeconds:220,practiceMinutes:10,focus:'Smooth chorus entrance',notes:'Start the chorus quietly, then build together.'},{id:crypto.randomUUID(),title:'Lantern Road',artist:'',key:'A minor',bpm:104,durationSeconds:245,practiceMinutes:12,focus:'A clean ending',notes:''}]};}
function verifyDuplicate(before,after,id){const i=before.songs.findIndex(s=>s.id===id);assert(i>=0);assert.equal(after.revision,before.revision+1);assert.equal(after.songs.length,before.songs.length+1);const copy=after.songs[i+1];assert(!before.songs.some(s=>s.id===copy.id));M.id(copy.id);assert.deepEqual({...copy,id},before.songs[i]);const expected=structuredClone(before);expected.revision++;expected.songs.splice(i+1,0,copy);assert.deepEqual(after,expected);return copy;}
async function unchanged(p,bytes){assert.deepEqual(await inspect(),p);assert.equal(hash(await fs.readFile(path.join(dataRoot,'project.json'))),hash(bytes));}
async function main(){await fs.mkdir(run,{recursive:true});beforeHashes=await fingerprint();report.sourceBefore=beforeHashes;
await check('0.1.1 version, stable ID/dataVersion, permissions and Node-only dependency',async()=>{const m=JSON.parse(await fs.readFile(path.join(source,'im.json'),'utf8')),p=JSON.parse(await fs.readFile(path.join(source,'package.json'),'utf8'));assert.equal(m.id,M.APP_ID);assert.equal(m.version,'0.1.1');assert.equal(p.version,'0.1.1');assert.equal(m.dataVersion,1);assert.equal(m.apiVersion,1);assert.deepEqual(m.permissions,['app-data:read-write','loopback:listen']);assert.deepEqual(m.dependencies,['node']);});
const oldRelease=path.join(run,'release-0.1.0');
await check('Old package preserved byte-for-byte; extract only its verified production files into test fixture',async()=>{const b=await fs.readFile(path.join(root,'evidence','previous-0.1.0.impack.json'));assert.equal(hash(b),'f0159a5ea7d29225ce61a0f867abec6cf980d8de6f5633971fb588d3d0666e8e');const p=JSON.parse(b);assert.equal(p.manifest.id,M.APP_ID);assert.equal(p.manifest.version,'0.1.0');assert.equal(p.sha256,'c5023902ac761d982628bae3d229bbea4da34784e852d913901e3c0bf5a49aab');assert.deepEqual(p.files.map(f=>f.path).sort(),Object.keys(beforeHashes).sort());await fs.mkdir(oldRelease);for(const f of p.files){assert(/^[A-Za-z0-9_.-]+$/.test(f.path));const bytes=Buffer.from(f.content,'base64');assert.equal(hash(bytes),f.sha256);assert.equal(bytes.length,f.bytes);await fs.writeFile(path.join(oldRelease,f.path),bytes,{flag:'wx'});}oldStart=require(path.join(oldRelease,'entry.cjs')).start;report.previousPackage={fileSha256:hash(b),contentHash:p.sha256,bytes:b.length};});
let oldProjectBytes,oldToken;
await check('Create synthetic revision-5 session and real HTML/JSON exports using pinned 0.1.0 code',async()=>{fixture=rehearsal();await fs.mkdir(dataRoot);await fs.writeFile(path.join(dataRoot,'project.json'),JSON.stringify(fixture,null,2)+'\n');app=await open(dataRoot,oldStart,oldRelease);const h=(await api('/api/health')).value;assert.equal(h.version,'0.1.0');token=h.token;oldToken=token;assert.deepEqual(await inspect(),fixture);for(const format of['html','json']){const r=await api('/api/export',{revision:5,format});assert.equal(r.status,201);assert.equal(hash(await fs.readFile(path.join(dataRoot,r.value.path))),r.value.sha256);oldExports.push(r.value);}oldProjectBytes=await fs.readFile(path.join(dataRoot,'project.json'));await close(app);});
await check('0.1.0 saved session, revision, IDs, notes and export bytes open unchanged in 0.1.1',async()=>{app=await open();const h=(await api('/api/health')).value;assert.equal(h.version,'0.1.1');token=h.token;assert.notEqual(token,oldToken);assert.deepEqual(await inspect(),fixture);assert.equal(hash(await fs.readFile(path.join(dataRoot,'project.json'))),hash(oldProjectBytes));assert.deepEqual((await api('/api/exports')).value.exports.map(e=>e.id).sort(),oldExports.map(e=>e.id).sort());for(const e of oldExports){assert.equal(hash((await api(e.url)).text),e.sha256);}assert.equal((await cli(['help'])).value.version,'0.1.1');assert((await cli(['help'])).value.commands['song duplicate']);assert.equal((await cli(['status'])).value.version,'0.1.1');});
let firstCopyId;
await check('Finite CLI duplicates every detail with a fresh ID immediately after the first song',async()=>{const before=await inspect();const after=(await cli(['song','duplicate',before.songs[0].id,'--revision',String(before.revision)])).value;const copy=verifyDuplicate(before,after,before.songs[0].id);firstCopyId=copy.id;assert.equal(copy.title,'Silver Compass');assert.deepEqual(await inspect(),after);report.firstDuplicate={revision:after.revision,originalId:before.songs[0].id,copyId:copy.id,position:2};});
await check('Duplicating the last song appends only its independent copy',async()=>{const before=await inspect(),id=before.songs.at(-1).id;const after=(await cli(['song','duplicate',id,'--revision',String(before.revision)])).value;verifyDuplicate(before,after,id);});
await check('Editing the copied song leaves the original and all other settings unchanged',async()=>{const before=await inspect(),after=(await cli(['song','edit',firstCopyId,'--notes','A separate practice pass.','--revision',String(before.revision)])).value;const expected=structuredClone(before);expected.revision++;expected.songs.find(s=>s.id===firstCopyId).notes='A separate practice pass.';assert.deepEqual(after,expected);assert.equal(after.songs[0].notes,fixture.songs[0].notes);});
await check('Missing, malformed, unknown and surplus CLI IDs/options fail without a saved mutation',async()=>{const p=await inspect(),b=await fs.readFile(path.join(dataRoot,'project.json'));const id=p.songs[0].id;for(const[args,error]of[[['song','duplicate'],'CLI_ARGUMENT'],[['song','duplicate','bad-id'],'INVALID_INPUT'],[['song','duplicate','../project.json'],'INVALID_INPUT'],[['song','duplicate',crypto.randomUUID()],'NOT_FOUND'],[['song','duplicate',id,id],'CLI_ARGUMENT'],[['song','duplicate',id,'--title','Do not rename'],'CLI_ARGUMENT'],[['song','duplicate',id,'--revision','0'],'INVALID_INPUT']])assert.equal((await cli(args,1)).value.error.code,error);await unchanged(p,b);});
await check('Raw duplicate actions reject absent/nonstring IDs, path input and unsupported fields',async()=>{const p=await inspect(),b=await fs.readFile(path.join(dataRoot,'project.json'));for(const action of[{action:'song.duplicate'},{action:'song.duplicate',id:null},{action:'song.duplicate',id:42},{action:'song.duplicate',id:'../../outside'},{action:'song.duplicate',id:crypto.randomUUID()},{action:'song.duplicate',id:p.songs[0].id,patch:{title:'No'}},{action:'song.duplicate',id:p.songs[0].id,to:1}])assert.equal((await api('/api/action',{revision:p.revision,...action})).status,422);await unchanged(p,b);});
await check('Stale CLI and stale authenticated duplicate requests return conflicts without extra copies',async()=>{const p=await inspect(),b=await fs.readFile(path.join(dataRoot,'project.json'));assert.equal((await cli(['song','duplicate',p.songs[0].id,'--revision',String(p.revision-1)],1)).value.error.code,'REVISION_CONFLICT');const r=await api('/api/action',{revision:p.revision-1,action:'song.duplicate',id:p.songs[0].id});assert.equal(r.status,409);assert.equal(r.value.error.currentRevision,p.revision);await unchanged(p,b);});
await check('Duplicate action retains authentication and foreign-origin protection',async()=>{const p=await inspect(),b=await fs.readFile(path.join(dataRoot,'project.json')),action={revision:p.revision,action:'song.duplicate',id:p.songs[0].id};for(const badToken of['','0'.repeat(64)])assert.equal((await api('/api/action',action,{},badToken)).status,401);assert.equal((await api('/api/action',action,{Origin:'http://not-the-app.invalid'})).status,403);await unchanged(p,b);});
await check('Concurrent finite duplication commands using one revision create exactly one copy',async()=>{const p=await inspect();const r=await Promise.all(p.songs.slice(0,2).map(s=>cli(['song','duplicate',s.id,'--revision',String(p.revision)],null)));assert.deepEqual(r.map(v=>v.code).sort(),[0,1]);assert.equal(r.find(v=>v.code===1).value.error.code,'REVISION_CONFLICT');const after=await inspect();assert.deepEqual(after,r.find(v=>v.code===0).value);assert.equal(after.revision,p.revision+1);assert.equal(after.songs.length,p.songs.length+1);});
await check('99 songs can duplicate to 100; CLI, action and full-draft attempts cannot exceed 100',async()=>{const mainApp=app,mainToken=token;try{app=await open(path.join(run,'limit-data'));token=(await api('/api/health')).value.token;let p=await inspect();p.songs=Array.from({length:99},(_,i)=>({...fixture.songs[0],id:crypto.randomUUID(),title:'Limit fixture '+(i+1)}));const seed=await api('/api/project',p);assert.equal(seed.status,200);p=seed.value;const hundred=(await cli(['song','duplicate',p.songs[0].id,'--revision',String(p.revision)])).value;verifyDuplicate(p,hundred,p.songs[0].id);assert.equal(hundred.songs.length,100);const bytes=await fs.readFile(path.join(run,'limit-data','project.json'));assert.equal((await cli(['song','duplicate',hundred.songs[0].id,'--revision',String(hundred.revision)],1)).value.error.code,'INVALID_INPUT');assert.equal((await api('/api/action',{revision:hundred.revision,action:'song.duplicate',id:hundred.songs[0].id})).status,422);const tooMany=structuredClone(hundred);tooMany.songs.push({...tooMany.songs[0],id:crypto.randomUUID()});assert.equal((await api('/api/project',tooMany)).status,422);assert.deepEqual(await inspect(),hundred);assert.equal(hash(await fs.readFile(path.join(run,'limit-data','project.json'))),hash(bytes));await close(app);}finally{app=mainApp;token=mainToken;}});
let upgradedState;
await check('Restart retains duplicated saved data and old immutable exports',async()=>{upgradedState=await inspect();const oldUrl=app.url;await close(app);app=await open();token=(await api('/api/health')).value.token;assert.deepEqual((await cli(['inspect'])).value,upgradedState);for(const e of oldExports)assert.equal(hash((await api(e.url)).text),e.sha256);report.compatibility={fixtureRevision:5,upgradedRevision:upgradedState.revision,songCount:upgradedState.songs.length,oldExportsUnchanged:true};});
await check('Unchanged dataVersion 1 is also readable by pinned 0.1.0 after duplication',async()=>{await close(app);app=await open(dataRoot,oldStart,oldRelease);token=(await api('/api/health')).value.token;assert.equal((await api('/api/health')).value.version,'0.1.0');assert.deepEqual(await inspect(),upgradedState);for(const e of oldExports)assert.equal(hash((await api(e.url)).text),e.sha256);await close(app);});
}
(async()=>{let failed=false;try{await main();}catch(e){failed=true;report.failure={message:e.message,stack:e.stack};console.error(e.stack);}finally{report.cleanup.serversClosed=true;for(const a of apps)try{await close(a);}catch(e){failed=true;report.cleanup.serversClosed=false;report.cleanup.error=e.message;}const leftover=[...children];for(const c of leftover)c.kill();await Promise.all(leftover.map(c=>new Promise(resolve=>{if(c.exitCode!==null||c.signalCode!==null)return resolve();const t=setTimeout(resolve,2000);c.once('close',()=>{clearTimeout(t);resolve();});})));report.cleanup.cliChildrenExited=children.size===0;if(!report.cleanup.cliChildrenExited)failed=true;report.sourceAfter=await fingerprint();report.sourceUnchanged=JSON.stringify(beforeHashes)===JSON.stringify(report.sourceAfter);if(!report.sourceUnchanged)failed=true;report.finishedAt=new Date().toISOString();report.passed=report.checks.filter(c=>c.passed).length;report.failed=report.checks.filter(c=>!c.passed).length;report.ok=!failed;await fs.mkdir(run,{recursive:true});await fs.writeFile(path.join(run,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:report.ok,passed:report.passed,failed:report.failed,report:path.relative(root,path.join(run,'result.json')),cleanup:report.cleanup,sourceUnchanged:report.sourceUnchanged},null,2));process.exitCode=failed?1:0;}})();
