'use strict';
(()=>{
  const $=id=>document.getElementById(id);let saved=null,draft=null,selected=null,token=null,dirty=false,busy=false,online=false;
  const length=s=>Number.isFinite(s)?Math.floor(s/60)+':'+String(s%60).padStart(2,'0'):'—';
  const elapsed=m=>Math.floor(m/60)+':'+String(m%60).padStart(2,'0');
  const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').className='message'+(error?' error':'');}
  function conflict(text){$('conflict').textContent=text;$('conflict').hidden=!text;}
  function status(){if(!saved){$('save-status').textContent=online?'Loading…':'Not connected';return;}$('save-status').textContent=busy?'Working…':dirty?'Unsaved changes':'Saved · revision '+saved.revision;$('save').disabled=busy||!dirty;$('draft-label').textContent=dirty?'Local draft · save to share with your AI':'Saved workspace · shared with your AI';$('revision-label').textContent='Saved revision '+saved.revision;$('connection-status').textContent=online?'Connected to your local workspace':'Connection lost · draft kept';}
  function lock(value){busy=value;for(const e of document.querySelectorAll('input,textarea,button')){if(value){e.dataset.lockDisabled=e.disabled?'1':'0';e.disabled=true;}else if(e.dataset.lockDisabled!==undefined){e.disabled=e.dataset.lockDisabled==='1';delete e.dataset.lockDisabled;}}status();}
  async function request(route,body){let r;try{r=await fetch(route,{method:body?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(5000),...(body?{headers:{'Content-Type':'application/json','x-app-token':token},body:JSON.stringify(body)}:{})});}catch{online=false;status();throw Error('The local app is not responding. Your unsaved draft is still here.');}let b;try{b=await r.json();}catch{throw Error('The app returned an unreadable response. Your draft is kept.');}online=true;if(!r.ok){const e=Error(b.error?.message||'Request failed.');e.code=b.error?.code;e.currentRevision=b.error?.currentRevision;throw e;}return b;}
  function schedule(){const blocks=[];let t=0;const add=(type,title,minutes,focus='',notes='')=>{if(!Number.isFinite(minutes)||minutes<=0)return;blocks.push({type,title,minutes,start:t,end:t+minutes,focus,notes});t+=minutes;};add('warmup','Warm-up & sound check',draft.warmupMinutes,'Tune, check levels, and settle into the session.');draft.songs.forEach((s,i)=>{add('song',s.title,s.practiceMinutes,s.focus,s.notes);if(draft.songs.length>1&&i+1===Math.ceil(draft.songs.length/2))add('break','Break',draft.breakMinutes,'Rest and reset.');});return{blocks,total:t};}
  function summaries(){if(!draft)return;const {blocks,total}=schedule();$('song-count').replaceChildren(document.createTextNode(String(draft.songs.length)+' '),node('small','',draft.songs.length===1?'song':'songs'));$('set-length').replaceChildren(document.createTextNode(length(draft.songs.reduce((n,s)=>n+s.durationSeconds,0))+' '),node('small','','min:sec'));$('session-length').replaceChildren(document.createTextNode(String(total)+' '),node('small','','min'));$('stamp-date').textContent=draft.sessionDate||'Undated session';$('plan-title').textContent=draft.name||'Session plan';$('plan-goal').textContent=draft.goal||'Add a session goal to keep your rehearsal focused.';$('plan-notes').textContent=draft.notes||'No session notes yet.';$('plan-explanation').textContent=dirty?'Preview of your draft. Save changes before exporting.':'A schedule built from your saved practice times.';
    $('schedule').replaceChildren();for(const b of blocks){const li=node('li',b.type);const time=node('div','time',elapsed(b.start)+'–'+elapsed(b.end));time.append(node('small','',b.minutes+' min'));const content=node('div');content.append(node('h4','',b.title));if(b.focus)content.append(node('p','pre',b.focus));if(b.notes)content.append(node('p','pre block-notes',b.notes));li.append(time,content);$('schedule').append(li);}if(!draft.songs.length)$('schedule').append(node('li','muted','Add a song to build your practice schedule.'));
  }
  function rows(){if(!draft)return;$('songs').replaceChildren();$('empty').hidden=draft.songs.length>0;$('add-song').disabled=busy||draft.songs.length>=100;$('duplicate-song').disabled=busy||draft.songs.length>=100||!draft.songs.some(s=>s.id===selected);$('duplicate-song').title=draft.songs.length>=100?'The set list already has 100 songs.':'Copy the selected song immediately after it.';
    draft.songs.forEach((s,i)=>{const li=node('li','song-row'+(s.id===selected?' selected':''));li.dataset.songId=s.id;const choose=node('button','song-select');choose.type='button';choose.setAttribute('aria-label','Edit '+(s.title||'Untitled song'));choose.setAttribute('aria-pressed',String(selected===s.id));choose.append(node('span','song-number',String(i+1).padStart(2,'0')));const copy=node('span','song-copy');copy.append(node('strong','',s.title||'Untitled song'));copy.append(node('span','song-meta',[s.artist,s.key,s.bpm===null?'':s.bpm+' BPM',length(s.durationSeconds),s.practiceMinutes+' min practice'].filter(Boolean).join(' · ')));if(s.focus)copy.append(node('span','song-focus',s.focus));choose.append(copy);choose.addEventListener('click',()=>{selected=s.id;rows();editor();});const arrows=node('div','song-arrows');for(const[delta,symbol,label]of[[-1,'↑','earlier'],[1,'↓','later']]){const b=node('button','',symbol);b.type='button';b.setAttribute('aria-label','Move '+(s.title||'song')+' '+label);b.disabled=busy||i+delta<0||i+delta>=draft.songs.length;b.addEventListener('click',()=>{draft.songs.splice(i+delta,0,draft.songs.splice(i,1)[0]);mark();rows();editor();});arrows.append(b);}li.append(choose,arrows);$('songs').append(li);});
  }
  function sessionFields(){for(const[id,key]of Object.entries({'session-name':'name','session-date':'sessionDate','session-goal':'goal','session-notes':'notes',warmup:'warmupMinutes',break:'breakMinutes'}))$(id).value=draft[key];}
  function editor(){const s=draft.songs.find(s=>s.id===selected);$('editor').hidden=!s;$('editor-empty').hidden=!!s;if(!s)return;$('editing-position').textContent='SONG '+String(draft.songs.indexOf(s)+1).padStart(2,'0')+' · DETAILS';for(const[id,key]of Object.entries({'song-title':'title','song-artist':'artist','song-key':'key','song-bpm':'bpm','song-practice':'practiceMinutes','song-focus':'focus','song-notes':'notes'}))$(id).value=s[key]===null?'':s[key];$('song-duration').value=length(s.durationSeconds);}
  function mark(){dirty=true;status();summaries();}
  // Selection stays browser-local. Recognize one isolated saved duplication from
  // another controller only when there is no local draft to protect.
  function externalDuplicate(p){
    if(dirty||!saved||p.revision!==saved.revision+1||p.songs.length!==saved.songs.length+1)return null;
    const added=p.songs.filter(s=>!saved.songs.some(old=>old.id===s.id));if(added.length!==1)return null;
    const copy=added[0],i=p.songs.indexOf(copy),original=p.songs[i-1];
    if(!original||JSON.stringify({...copy,id:original.id})!==JSON.stringify(original))return null;
    const withoutCopy={...p,revision:saved.revision,songs:p.songs.filter(s=>s.id!==copy.id)};
    return JSON.stringify(withoutCopy)===JSON.stringify(saved)?copy.id:null;
  }
  function accept(p){const duplicateId=externalDuplicate(p);if(duplicateId)selected=duplicateId;saved=structuredClone(p);draft=structuredClone(p);if(!draft.songs.some(s=>s.id===selected))selected=draft.songs[0]?.id||null;dirty=false;conflict('');sessionFields();rows();editor();summaries();status();}
  async function load(){const h=await request('/api/health');if(h.app!=='im-0712156b51184988ba41d5d8d0697af6')throw Error('This is not the expected rehearsal workspace.');const p=await request('/api/project');token=h.token;accept(p);await exportsList();}
  async function exportsList(){const {exports}=await request('/api/exports');$('exports').replaceChildren();if(!exports.length)$('exports').append(node('p','field-hint','No exports yet. Save your set, then make a plan.'));for(const e of exports.slice(0,20)){const box=node('div','export-item');box.append(node('strong','',e.format.toUpperCase()+' · revision '+e.revision+' · '+e.name));box.append(node('small','',new Date(e.createdAt).toLocaleString()+' · '+e.bytes.toLocaleString()+' bytes'));if(/^[a-f0-9-]{36}$/.test(e.id)){if(e.format==='html'){const a=node('a','','Open printable plan');a.href='/api/exports/'+e.id;a.target='_blank';a.rel='noopener';box.append(a);}const download=node('a','','Download '+e.format.toUpperCase());download.href='/api/exports/'+e.id+'/download';box.append(download);}$('exports').append(box);}if(exports.length>20)$('exports').append(node('p','field-hint','Showing the latest 20. The CLI exports command lists all snapshots.'));}
  for(const[id,key]of Object.entries({'session-name':'name','session-date':'sessionDate','session-goal':'goal','session-notes':'notes',warmup:'warmupMinutes',break:'breakMinutes'}))$(id).addEventListener('input',()=>{if(!draft)return;draft[key]=['warmup','break'].includes(id)?($(id).value===''?NaN:Number($(id).value)):$(id).value;mark();});
  for(const[id,key]of Object.entries({'song-title':'title','song-artist':'artist','song-key':'key','song-bpm':'bpm','song-practice':'practiceMinutes','song-focus':'focus','song-notes':'notes','song-duration':'durationSeconds'}))$(id).addEventListener('input',()=>{const s=draft?.songs.find(s=>s.id===selected);if(!s)return;const value=$(id).value;if(id==='song-duration'){const m=/^(\d+):([0-5]\d)$/.exec(value);s[key]=m?Number(m[1])*60+Number(m[2]):NaN;}else if(id==='song-practice')s[key]=value===''?NaN:Number(value);else if(id==='song-bpm')s[key]=value===''?null:Number(value);else s[key]=value;mark();rows();});
  function add(){if(!draft||busy||draft.songs.length>=100)return;selected=crypto.randomUUID();draft.songs.push({id:selected,title:'New song',artist:'',key:'',bpm:null,durationSeconds:180,practiceMinutes:10,focus:'',notes:''});mark();rows();editor();$('song-title').focus();$('song-title').select();}
  $('add-song').addEventListener('click',add);$('empty-add').addEventListener('click',add);
  $('duplicate-song').addEventListener('click',()=>{
    if(!draft||busy)return;const i=draft.songs.findIndex(s=>s.id===selected);if(i<0)return;
    if(draft.songs.length>=100){message('The set list already has 100 songs.',true);return;}
    const copy=structuredClone(draft.songs[i]);copy.id=crypto.randomUUID();draft.songs.splice(i+1,0,copy);selected=copy.id;
    mark();rows();editor();message('Duplicated “'+copy.title+'” in your draft. Save changes to share it.');$('song-title').focus();$('song-title').select();
  });
  $('remove-song').addEventListener('click',()=>{const s=draft.songs.find(s=>s.id===selected);if(!s||!confirm('Remove “'+s.title+'” from this draft? Save changes to make it permanent.'))return;const i=draft.songs.indexOf(s);draft.songs.splice(i,1);selected=draft.songs[Math.min(i,draft.songs.length-1)]?.id||null;mark();rows();editor();});
  async function save(){if(!draft||busy||!dirty)return;if(!$('session-form').reportValidity()||(!$('editor').hidden&&!$('song-form').reportValidity())){message('Check the highlighted field before saving.',true);return;}lock(true);message('');try{const next=await request('/api/project',structuredClone(draft));accept(next);message('Saved. Your set list and practice notes are now shared.');}catch(e){if(e.code==='REVISION_CONFLICT')conflict('Your AI or another window saved revision '+e.currentRevision+'. Your draft has not been replaced. Review/copy your draft, then use Reload latest only when ready to discard it.');message(e.message,true);}finally{lock(false);rows();}}
  $('save').addEventListener('click',save);for(const id of['session-form','song-form'])$(id).addEventListener('submit',e=>{e.preventDefault();save();});
  $('reload').addEventListener('click',async()=>{if(busy)return;if(dirty&&!confirm('Discard your unsaved draft and load the latest saved session?'))return;lock(true);try{await load();message('Loaded the latest saved session.');}catch(e){message(e.message,true);}finally{lock(false);rows();}});
  for(const mode of['workshop','plan'])$('tab-'+mode).addEventListener('click',()=>{$('workshop').hidden=mode!=='workshop';$('plan-view').hidden=mode!=='plan';for(const m of['workshop','plan']){$('tab-'+m).classList.toggle('active',m===mode);$('tab-'+m).setAttribute('aria-pressed',String(m===mode));}if(mode==='plan'){summaries();exportsList().catch(e=>message(e.message,true));}});
  async function exportPlan(format){if(!saved||busy)return;if(dirty){message('Save your changes before exporting this plan.',true);return;}lock(true);try{const r=await request('/api/export',{revision:saved.revision,format});await exportsList();message('Exported '+format.toUpperCase()+' from revision '+r.revision+'. Open or download it under Saved snapshots.');}catch(e){message(e.message,true);if(e.code==='REVISION_CONFLICT')conflict('The saved session changed. Reload latest before exporting.');}finally{lock(false);rows();}}
  $('export-html').addEventListener('click',()=>exportPlan('html'));$('export-json').addEventListener('click',()=>exportPlan('json'));
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  let timer;async function poll(){if(saved&&!busy&&!document.hidden){try{const p=await request('/api/project');if(p.revision!==saved.revision){if(dirty)conflict('A new saved revision ('+p.revision+') is available. Your unsaved draft is kept. Reload latest only when ready to discard your draft.');else{accept(p);message('Updated from the shared workspace.');await exportsList();}}status();}catch{online=false;status();}}timer=setTimeout(poll,2000);}
  window.addEventListener('pagehide',()=>clearTimeout(timer));window.addEventListener('pageshow',e=>{if(e.persisted)poll();});
  load().then(()=>{message('');poll();}).catch(e=>{message(e.message,true);status();});
})();
