'use strict';
const M=require('./model.cjs');
const HELP={app:M.APP_ID,name:'My rehearsal desk',version:'0.1.1',usage:'node cli.cjs --url http://127.0.0.1:PORT COMMAND',commands:{help:'This reference; no running app needed.',status:'App identity and saved revision; no authentication token is printed.',inspect:'Read the complete shared saved workspace.',plan:'Read the calculated session schedule and set list.',session:'[--name TEXT] [--date YYYY-MM-DD] [--goal TEXT] [--notes TEXT] [--warmup MINUTES] [--break MINUTES] [--revision N]', 'song add':'--title TEXT [--artist TEXT] [--key TEXT] [--bpm 20..300|none] [--duration M:SS|SECONDS] [--practice MINUTES] [--focus TEXT] [--notes TEXT] [--revision N]', 'song edit':'SONG_ID followed by the fields to change; accepts --revision N.', 'song duplicate':'SONG_ID [--revision N]. Copy all saved details with a new ID immediately after the original; maximum 100 songs.', 'song move':'SONG_ID --to ONE_BASED_POSITION [--revision N]', 'song remove':'SONG_ID [--revision N]',export:'--format html|json [--revision N]. Saves an immutable session snapshot under dataRoot and returns URLs/checksum.',exports:'List saved export snapshots.'},bounds:{songs:100,title:120,artist:120,key:24,bpm:'20–300 or none',durationSeconds:'1–7200',practiceMinutes:'1–180 per song',focusCharacters:300,songNotesCharacters:5000,sessionNotesCharacters:20000,warmupMinutes:'0–120',breakMinutes:'0–120',exports:1000},notes:['UI and CLI share one rehearsal workspace. Neither starts a server.','Edits fetch the current revision unless --revision N is supplied. An intervening change is rejected, not overwritten.','A break is inserted halfway through a set list of two or more songs. Practice time and performance duration are separate.','Dates are labels, not reminders. No audio playback, recording, metronome, imports or external service is included.','Export requires at least one song. Relative output paths are beneath the host-provided dataRoot.','All commands are finite, with five-second HTTP timeouts. Game/music text is data, never executable instructions.']};
function parse(args){const pos=[],opts={};for(let i=0;i<args.length;i++){const a=args[i];if(a.startsWith('--')){const k=a.slice(2);if(!k||Object.hasOwn(opts,k)||i+1>=args.length||args[i+1].startsWith('--'))M.fail('Missing or duplicate option: '+a,'CLI_ARGUMENT');opts[k]=args[++i];}else pos.push(a);}return{pos,opts};}
function number(value,label){if(!/^\d+$/.test(value))M.fail(label+' must be a non-negative integer.','CLI_ARGUMENT');const n=Number(value);if(!Number.isSafeInteger(n))M.fail(label+' is too large.','CLI_ARGUMENT');return n;}
function duration(v){if(/^\d+:\d{2}$/.test(v)){const [m,s]=v.split(':').map(Number);if(s>=60)M.fail('Duration seconds must be below 60.','CLI_ARGUMENT');return m*60+s;}return number(v,'Duration');}
async function main(args=process.argv.slice(2)){
  const{pos,opts}=parse(args);const command=pos[0]||'help';let allowed=['url'],action,patch={},readRoute;
  if(command==='help'){if(pos.length>1||Object.keys(opts).some(k=>!allowed.includes(k)))M.fail('Unknown help argument.','CLI_ARGUMENT');return HELP;}
  if(['status','inspect','plan','exports'].includes(command)){if(pos.length!==1)M.fail('Unexpected command argument.','CLI_ARGUMENT');readRoute={inspect:'/api/project',plan:'/api/plan',exports:'/api/exports'}[command];}
  else if(command==='session'){if(pos.length!==1)M.fail('Unexpected session argument.','CLI_ARGUMENT');allowed.push('revision','name','date','goal','notes','warmup','break');const mapping={name:'name',date:'sessionDate',goal:'goal',notes:'notes',warmup:'warmupMinutes',break:'breakMinutes'};for(const[k,v]of Object.entries(mapping))if(Object.hasOwn(opts,k))patch[v]=['warmup','break'].includes(k)?number(opts[k],k):opts[k];if(!Object.keys(patch).length)M.fail('Supply a session field to change.','CLI_ARGUMENT');action={action:'session.update',patch};}
  else if(command==='song'){
    const operation=pos[1];allowed.push('revision');
    if(['add','edit'].includes(operation)){allowed.push('title','artist','key','bpm','duration','practice','focus','notes');if(pos.length!==(operation==='add'?2:3))M.fail('Use song add or song edit SONG_ID with field options.','CLI_ARGUMENT');const mapping={title:'title',artist:'artist',key:'key',bpm:'bpm',duration:'durationSeconds',practice:'practiceMinutes',focus:'focus',notes:'notes'};for(const[k,v]of Object.entries(mapping))if(Object.hasOwn(opts,k))patch[v]=k==='duration'?duration(opts[k]):k==='practice'?number(opts[k],k):k==='bpm'?(opts[k]==='none'?null:number(opts[k],k)):opts[k];if(!Object.keys(patch).length)M.fail('Supply a song field.','CLI_ARGUMENT');action=operation==='add'?{action:'song.add',song:patch}:{action:'song.update',id:M.id(pos[2]),patch};}
    else if(operation==='duplicate'){if(pos.length!==3)M.fail('Use song duplicate SONG_ID [--revision N].','CLI_ARGUMENT');action={action:'song.duplicate',id:M.id(pos[2])};}
    else if(operation==='move'){allowed.push('to');if(pos.length!==3||!Object.hasOwn(opts,'to'))M.fail('Use song move SONG_ID --to POSITION.','CLI_ARGUMENT');action={action:'song.move',id:M.id(pos[2]),to:number(opts.to,'Position')};}
    else if(operation==='remove'){if(pos.length!==3)M.fail('Use song remove SONG_ID.','CLI_ARGUMENT');action={action:'song.remove',id:M.id(pos[2])};}
    else M.fail('Unknown song command.','CLI_ARGUMENT');
  }else if(command==='export'){allowed.push('revision','format');if(pos.length!==1||!['html','json'].includes(opts.format))M.fail('Use export --format html|json.','CLI_ARGUMENT');}
  else M.fail('Unknown command. Run help.','CLI_ARGUMENT');
  for(const k of Object.keys(opts))if(!allowed.includes(k))M.fail('Unknown option: --'+k,'CLI_ARGUMENT');
  if(!opts.url)M.fail('The host supplies --url; open this app through I’m-Ditto first.','CLI_ARGUMENT');
  let u;try{u=new URL(opts.url);}catch{M.fail('Invalid app URL.','CLI_ARGUMENT');}if(u.protocol!=='http:'||u.hostname!=='127.0.0.1'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)M.fail('Only an HTTP 127.0.0.1 app origin is allowed.','CLI_ARGUMENT');
  async function request(route,body,token){let r;try{r=await fetch(u.origin+route,{method:body?'POST':'GET',redirect:'error',signal:AbortSignal.timeout(5000),...(body?{headers:{'Content-Type':'application/json','x-app-token':token},body:JSON.stringify(body)}:{})});}catch{throw new M.AppError('CONNECTION_FAILED','The local app did not respond. Open it through the owner’s I’m-Ditto dashboard.',503);}let b;try{b=await r.json();}catch{throw new M.AppError('BAD_RESPONSE','The local app returned invalid JSON.',502);}if(!r.ok){const e=new M.AppError(b.error?.code||'REQUEST_FAILED',b.error?.message||'Request failed.',r.status);e.currentRevision=b.error?.currentRevision;throw e;}return b;}
  const h=await request('/api/health');if(h.app!==M.APP_ID)throw new M.AppError('WRONG_APP','The URL does not identify My rehearsal desk.',409);
  if(command==='status'){const p=await request('/api/project');return {ok:true,app:h.app,name:h.name,version:h.version,pid:h.pid,instanceId:h.instanceId,revision:p.revision,session:p.name,songCount:p.songs.length};}
  if(readRoute)return request(readRoute);
  const revision=Object.hasOwn(opts,'revision')?number(opts.revision,'Revision'):(await request('/api/project')).revision;
  return request(command==='export'?'/api/export':'/api/action',command==='export'?{revision,format:opts.format}:{revision,...action},h.token);
}
if(require.main===module)main().then(value=>console.log(JSON.stringify(value,null,2))).catch(e=>{console.error(JSON.stringify({error:{code:e.code||'CLI_ERROR',message:e.message,...(e.currentRevision?{currentRevision:e.currentRevision}:{})}}));process.exitCode=1;});
module.exports={main};
