'use strict';
const {randomUUID}=require('node:crypto');
const APP_ID='im-0712156b51184988ba41d5d8d0697af6';
class AppError extends Error { constructor(code,message,status=422){super(message);this.code=code;this.status=status;} }
const fail=(message,code='INVALID_INPUT')=>{throw new AppError(code,message);};
const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
function keys(v,allowed,label){if(!record(v))fail(label+' must be an object.');for(const k of Object.keys(v))if(!allowed.includes(k))fail('Unknown '+label+' field: '+k);}
function text(v,label,max,required=false){if(typeof v!=='string'||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(v))fail(label+' must be text of at most '+max+' characters.');if(required&&!v.trim())fail(label+' is required.');return v;}
function integer(v,label,min,max){if(!Number.isSafeInteger(v)||v<min||v>max)fail(label+' must be an integer from '+min+' to '+max+'.');return v;}
function id(v){if(typeof v!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v))fail('Invalid song/export ID.');return v;}
function date(v){text(v,'Session date',10);if(v==='')return v;if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)fail('Session date must be a real date in YYYY-MM-DD form, or empty.');return v;}
const SONG_FIELDS=['title','artist','key','bpm','durationSeconds','practiceMinutes','focus','notes'];
const PROJECT_FIELDS=['name','sessionDate','goal','notes','warmupMinutes','breakMinutes','songs'];
function song(s){keys(s,['id',...SONG_FIELDS],'song');id(s.id);text(s.title,'Song title',120,true);text(s.artist,'Artist',120);text(s.key,'Key',24);if(s.bpm!==null)integer(s.bpm,'Tempo',20,300);integer(s.durationSeconds,'Song length in seconds',1,7200);integer(s.practiceMinutes,'Practice minutes',1,180);text(s.focus,'Practice focus',300);text(s.notes,'Song notes',5000);return s;}
function project(p){keys(p,['schemaVersion','revision',...PROJECT_FIELDS],'project');if(p.schemaVersion!==1)fail('Unsupported project schema.');integer(p.revision,'Revision',1,Number.MAX_SAFE_INTEGER-1);text(p.name,'Session name',100,true);date(p.sessionDate);text(p.goal,'Session goal',500);text(p.notes,'Session notes',20000);integer(p.warmupMinutes,'Warm-up minutes',0,120);integer(p.breakMinutes,'Break minutes',0,120);if(!Array.isArray(p.songs)||p.songs.length>100)fail('A set list supports up to 100 songs.');const ids=new Set();for(const s of p.songs){song(s);if(ids.has(s.id))fail('Duplicate song ID.');ids.add(s.id);}return structuredClone(p);}
function initial(){return {schemaVersion:1,revision:1,name:'My rehearsal desk',sessionDate:'',goal:'',notes:'',warmupMinutes:5,breakMinutes:5,songs:[]};}
function load(raw){if(record(raw)&&Object.keys(raw).every(k=>['revision','name','notes'].includes(k))&&Object.keys(raw).length===3)return project({...initial(),...raw});return project(raw);}
function apply(current,body){keys(body,['revision','action','patch','song','id','to'],'action');integer(body.revision,'Revision',1,Number.MAX_SAFE_INTEGER-1);const p=structuredClone(current);let allowed;
  switch(body.action){
    case 'session.update':allowed=['revision','action','patch'];keys(body.patch,PROJECT_FIELDS.filter(k=>k!=='songs'),'session patch');if(!Object.keys(body.patch).length)fail('Supply a session field to change.');Object.assign(p,body.patch);break;
    case 'song.add':allowed=['revision','action','song'];keys(body.song,SONG_FIELDS,'new song');if(p.songs.length>=100)fail('The set list already has 100 songs.');p.songs.push({id:randomUUID(),title:'',artist:'',key:'',bpm:null,durationSeconds:180,practiceMinutes:10,focus:'',notes:'',...body.song});break;
    case 'song.duplicate':{allowed=['revision','action','id'];id(body.id);const i=p.songs.findIndex(s=>s.id===body.id);if(i<0)fail('Song not found.','NOT_FOUND');if(p.songs.length>=100)fail('The set list already has 100 songs.');const copy=structuredClone(p.songs[i]);copy.id=randomUUID();p.songs.splice(i+1,0,copy);break;}
    case 'song.update':{allowed=['revision','action','id','patch'];id(body.id);keys(body.patch,SONG_FIELDS,'song patch');if(!Object.keys(body.patch).length)fail('Supply a song field to change.');const s=p.songs.find(s=>s.id===body.id);if(!s)fail('Song not found.','NOT_FOUND');Object.assign(s,body.patch);break;}
    case 'song.move':{allowed=['revision','action','id','to'];id(body.id);integer(body.to,'Position',1,p.songs.length);const i=p.songs.findIndex(s=>s.id===body.id);if(i<0)fail('Song not found.','NOT_FOUND');p.songs.splice(body.to-1,0,p.songs.splice(i,1)[0]);break;}
    case 'song.remove':{allowed=['revision','action','id'];id(body.id);const i=p.songs.findIndex(s=>s.id===body.id);if(i<0)fail('Song not found.','NOT_FOUND');p.songs.splice(i,1);break;}
    default:fail('Unknown action.');
  }
  keys(body,allowed,'action');p.revision=current.revision+1;return project(p);
}
function plan(p){const blocks=[];let elapsed=0;const add=(type,title,minutes,focus='',notes='',songId=null)=>{if(!minutes)return;blocks.push({type,title,startMinute:elapsed,endMinute:elapsed+minutes,minutes,focus,notes,songId});elapsed+=minutes;};
  add('warmup','Warm-up & sound check',p.warmupMinutes,'Tune, check levels, and settle into the session.');
  p.songs.forEach((s,i)=>{add('song',s.title,s.practiceMinutes,s.focus,s.notes,s.id);if(p.songs.length>1&&i+1===Math.ceil(p.songs.length/2))add('break','Break',p.breakMinutes,'Rest and reset.');});
  return {name:p.name,sessionDate:p.sessionDate,revision:p.revision,goal:p.goal,notes:p.notes,songCount:p.songs.length,setDurationSeconds:p.songs.reduce((n,s)=>n+s.durationSeconds,0),practiceMinutes:p.songs.reduce((n,s)=>n+s.practiceMinutes,0),totalMinutes:elapsed,blocks,setList:p.songs.map((s,i)=>({position:i+1,...s}))};
}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const length=s=>Math.floor(s/60)+':'+String(s%60).padStart(2,'0');
const elapsed=m=>Math.floor(m/60)+':'+String(m%60).padStart(2,'0');
function exportContent(p,format){if(!p.songs.length)fail('Add at least one song before exporting a session plan.','EMPTY_SET_LIST');const q=plan(p);
  if(format==='json')return JSON.stringify({format:'rehearsal-desk-session-v1',project:p,plan:q},null,2)+'\n';
  if(format!=='html')fail('Export format must be html or json.');
  return '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(p.name)+' — session plan</title><style>'+PRINT_CSS+'</style></head><body><main><header><p class="eyebrow">MY REHEARSAL DESK · SESSION PLAN · REVISION '+p.revision+'</p><h1>'+escape(p.name)+'</h1><p>'+escape(p.sessionDate||'Undated session')+' · '+p.songs.length+' songs · '+length(q.setDurationSeconds)+' set length · '+q.totalMinutes+' min rehearsal</p></header>'+(p.goal?'<section><h2>Today’s goal</h2><p class="pre">'+escape(p.goal)+'</p></section>':'')+'<section><h2>Set list</h2><table><thead><tr><th>#</th><th>Song / artist</th><th>Key</th><th>Tempo</th><th>Length</th></tr></thead><tbody>'+p.songs.map((s,i)=>'<tr><td>'+(i+1)+'</td><td><strong>'+escape(s.title)+'</strong>'+(s.artist?'<br>'+escape(s.artist):'')+'</td><td>'+escape(s.key||'—')+'</td><td>'+(s.bpm===null?'—':s.bpm+' BPM')+'</td><td>'+length(s.durationSeconds)+'</td></tr>').join('')+'</tbody></table></section><section><h2>Practice schedule</h2><p class="muted">Elapsed time is hours:minutes from the start of rehearsal. Song lengths above are minutes:seconds.</p>'+q.blocks.map(b=>'<article class="block"><p class="timing">'+elapsed(b.startMinute)+'–'+elapsed(b.endMinute)+' · '+b.minutes+' min</p><h3>'+escape(b.title)+'</h3>'+(b.focus?'<p class="pre">'+escape(b.focus)+'</p>':'')+(b.notes?'<div class="note pre">'+escape(b.notes)+'</div>':'')+'</article>').join('')+'</section>'+(p.notes?'<section><h2>Session notes</h2><p class="pre">'+escape(p.notes)+'</p></section>':'')+'<footer>Saved snapshot · My rehearsal desk · Print with your browser’s Print command. No external assets.</footer></main></body></html>\n';
}
const PRINT_CSS=':root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f3f0e8;color:#242621;font:15px/1.6 system-ui,sans-serif}main{max-width:900px;margin:32px auto;padding:48px;background:white;border:1px solid #ddd9ce}h1{font:700 42px/1.12 Georgia,serif;margin:12px 0 20px;overflow-wrap:anywhere}h2{font-size:20px;margin-top:32px;border-bottom:1px solid #d9d7ce;padding-bottom:8px}h3{margin:4px 0;font-size:17px}.eyebrow{font-size:11px;letter-spacing:2px;color:#526653}.pre{white-space:pre-wrap;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #deddd5;padding:9px 6px;overflow-wrap:anywhere}th{font-size:12px;color:#62665c}th:first-child{width:6%}th:nth-child(2){width:47%}th:nth-child(3){width:13%}th:nth-child(4){width:18%}.block{padding:14px 0;border-bottom:1px solid #ddd}.timing{font-size:12px;font-weight:700;color:#47654d;margin:0}.note{padding:12px;background:#f2f4ed;border-left:3px solid #728967}.muted,footer{color:#64685f;font-size:12px}footer{margin-top:36px}thead{display:table-header-group}@page{size:A4;margin:16mm}@media print{body{background:white;font-size:10pt}main{border:0;margin:0;padding:0;max-width:none}h1{font-size:28pt}h2,h3{break-after:avoid}tr{break-inside:avoid}.block{break-inside:auto}.timing{break-after:avoid}p{orphans:3;widows:3}footer{font-size:8pt}}@media(max-width:600px){main{margin:0;padding:20px}h1{font-size:30px}th,td{padding:6px 3px;font-size:12px}}';
module.exports={APP_ID,AppError,fail,keys,text,integer,id,project,initial,load,apply,plan,exportContent,SONG_FIELDS,PROJECT_FIELDS};
